window.CINEMATIC_PROJECTS = [
  {
    id: 'social-resort',
    title: 'Social Media & Resort Concept Design',
    category: 'Visual Identity',
    year: '2025',
    description: 'Projeto de identidade visual e social media inspirado no pinguim-de-Magalhães 🐧✨',
    hero: 'img/Litoral Magalhão design.jpg',
    gallery: ['projeto07.img/01.jpg', 'projeto07.img/02.jpg', 'projeto07.img/03.jpg', 'projeto07.img/04.jpg'],
    concept: 'Uma narrativa visual que trabalha imagem, clima e posicionamento editorial em um universo de resort elegante.',
    brief: 'Identidade conceitual para comunicação social com cores ricas, superfícies texturizadas e movimento sutil.',
    breakdown: 'A peça explora ritmo lento, hierarquia dramática e detalhes refinados para evocar um trailer de marca.',
    final: 'Uma composição final que se abre como um frame de cinema, revelando a marca em pleno foco.'
  },
  {
    id: 'atomic-diner',
    title: 'Branding Retrô | Atomic Diner – Identidade Completa',
    category: 'Branding',
    year: '2025',
    description: 'A identidade visual do Atomic Diner, inspirada nas hamburguerias americanas dos anos 50.',
    hero: 'img/01.jpg',
    gallery: ['projeto08.img/01.jpg', 'projeto08.img/07.jpg', 'projeto08.img/09.jpg', 'projeto08.img/10.jpg'],
    concept: 'Uma reconstrução retrô cinematográfica, onde neon e textura se combinam para contar uma história de marca.',
    brief: 'O projeto foca em clima nostálgico, direção de arte marcante e um sistema visual coeso para múltiplos pontos de contato.',
    breakdown: 'Tipografia de impacto, paleta contrastada e sobreposições de luz são usados para criar uma experiência viva.',
    final: 'O frame final reúne a identidade em um visual forte e memorável, como um pôster de filme clássico.'
  },
  {
    id: 'pragx',
    title: 'PragX – Proteção Profissional contra Pragas',
    category: 'Brand System',
    year: '2024',
    description: 'Este projeto foi desenvolvido para uma empresa do segmento de controle de pragas urbanas.',
    hero: 'img/PragX03.png',
    gallery: ['projeto11.img/PragX01.png', 'projeto11.img/PragX02.jpg', 'projeto11.img/PragX03.png'],
    concept: 'Uma linguagem visual corporativa com atitude e clareza para um serviço de proteção profissional.',
    brief: 'Construção de identidade para transmitir confiança, eficiência e sofisticado controle visual.',
    breakdown: 'O uso de contraste, layout modular e elementos icônicos cria ritmo e presença de marca.',
    final: 'A peça final reforça o posicionamento com uma entrega limpa e cinematográfica.'
  },
  {
    id: 'sorriso-saude',
    title: 'Projeto pessoal — Sorriso & Saúde Odontologia',
    category: 'Identity Concept',
    year: '2025',
    description: 'Identidade visual desenvolvida para uma clínica fictícia de odontologia.',
    hero: 'projeto14.img/10.jpg',
    gallery: ['projeto14.img/05.jpg', 'projeto14.img/07.jpg', 'projeto14.img/08.jpg', 'projeto14.img/09.jpg'],
    concept: 'Uma marca construída em torno de confiança e elegância, com cuidado visual para cada frame.',
    brief: 'Direção de arte para um serviço que precisa ser visto como premium, acolhedor e moderno.',
    breakdown: 'Formas suaves, espaço respirado e contrastes sutis ajudam a manter uma estética cinematográfica.',
    final: 'Uma conclusão refinada que celebra o design através de uma apresentação limpa e impactante.'
  },
  {
    id: 'film-by-sam-mendes',
    title: 'A FILM BY SAM MENDES',
    category: 'Poster Art',
    year: '2025',
    description: '1917 – Pôster conceitual (arte digital semi-realista).',
    hero: 'projeto12.img/1917 01.jpg',
    gallery: ['projeto12.img/1917 02.jpg', 'projeto12.img/1917 03.jpg', 'projeto12.img/1917 04.jpg', 'projeto12.img/1917 05.jpg'],
    concept: 'Um cartaz inspirado pela narrativa de guerra, com luz direcional e atmosfera cinemática.',
    brief: 'O trabalho explora drama visual e foco em composição para criar uma peça impactante e emocional.',
    breakdown: 'A imagem trabalha movimento implícito e tonalidade clássica para uma estética poderosa.',
    final: 'A cena final se desdobra como um frame editorial, forte e memorável.'
  },
  {
    id: 'mandalorian',
    title: 'The Mandalorian — Poster Art',
    category: 'Concept Illustration',
    year: '2025',
    description: 'Original do universo Star Wars.',
    hero: 'projeto02.img/The Mandalorian 01.jpg',
    gallery: ['projeto02.img/01.jpg', 'projeto02.img/02.jpg', 'projeto02.img/03.jpg', 'projeto02.img/04.jpg'],
    concept: 'Uma obra inspirada em sci-fi, com presença dramática e energia visual pausada.',
    brief: 'Direção de arte para um poster que precisa combinar universo, luz e narrativa em uma só imagem.',
    breakdown: 'O trabalho utiliza profundidade atmosférica e contraste para guiar o olhar do espectador.',
    final: 'O resultado final assume o visual de um trailer estático, cheio de promessa e mistério.'
  },
  {
    id: 'avatar-water',
    title: 'Avatar: Art — The Way of Water',
    category: 'Visual Experiment',
    year: '2024',
    description: 'Art inspired by the universe of Avatar: The Way of Water.',
    hero: 'img/avatar 01.jpg',
    gallery: ['projeto01.img/01.png', 'projeto01.img/02.png', 'projeto01.img/03.png', 'projeto01.img/04.png'],
    concept: 'Um conceito visual que busca a fluidez do universo aquático em cada frame.',
    brief: 'A arte explora atmosfera e detalhe para criar uma peça sensorial e envolvente.',
    breakdown: 'Movimento suave, texturas imersivas e cenários etéreos constroem a narrativa.',
    final: 'A cena final coroada revela uma imagem ampla e cinematográfica.'
  },
  {
    id: 'formula-1',
    title: 'Formula 1 Visual Design',
    category: 'Sport / Speed',
    year: '2024',
    description: 'SPEED & PERFORMANCE Formula 1 Visual Identity.',
    hero: 'img/Max Verstappen.jpg',
    gallery: ['projeto03.img/01.jpg', 'projeto03.img/02.jpg', 'projeto06.img/Hamilton 01.jpg', 'img/Hamilton 2.jpg'],
    concept: 'Uma direção visual que traduz velocidade em luz, forma e cor.',
    brief: 'O projeto cria uma linguagem para performance e movimento em escala editorial.',
    breakdown: 'Elementos diagonais, cortes e foco rápido são usados para reforçar a emoção da pista.',
    final: 'Uma imagem final que intensifica a sensação de velocidade e drama.'
  },
  {
    id: 'william-lima',
    title: 'Variações Visuais | William Lima',
    category: 'Character Design',
    year: '2025',
    description: 'Três variações de personagem desenvolvidas a partir de photobash.',
    hero: 'projeto04.img/01.jpg',
    gallery: ['projeto04.img/william lima DESIGN 03.jpg', 'projeto04.img/william lima DESIGN 04.jpg', 'projeto04.img/11625149 copiar.jpg'],
    concept: 'Uma série de personagens feita para funcionar como narrativas visuais em movimento.',
    brief: 'O foco foi criar textura, personalidade e storytelling em cada composição.',
    breakdown: 'Luz dramática e escala pictórica organizam cada frame como uma sequência.' ,
    final: 'Uma conclusão que transforma cada personagem em um ponto alto cinematográfico.'
  },
  {
    id: 'stage-4',
    title: 'Stage 4 – Glacial Sector',
    category: 'Digital Manipulation',
    year: '2025',
    description: 'É um projeto de manipulação digital com foco em narrativa visual.',
    hero: 'projeto05.img/Stage 4 – Glacial Sector.jpg',
    gallery: ['projeto05.img/CAR 01.jpg', 'projeto05.img/CAR 02.jpg', 'projeto05.img/03.png', 'projeto05.img/04.png'],
    concept: 'Um universo futurista frio, onde veículos e arquitetura criam uma estética imersiva.',
    brief: 'A peça explora o contraste entre tecnologia, gelo e narrativa visual cinematográfica.',
    breakdown: 'Composições angulares e espaço negativo dão ritmo às imagens.' ,
    final: 'O frame final revela um ambiente grandioso e cheio de tensão visual.'
  },
  {
    id: 'cairo-gp',
    title: 'Cairo GP — Visual Concept',
    category: 'Speed Concept',
    year: '2024',
    description: 'Como seria uma corrida de Fórmula 1 no Egito?',
    hero: 'img/Hamilton 2.jpg',
    gallery: ['projeto06.img/Hamilton 01.jpg', 'projeto05.img/CAR 01.jpg', 'img/Max Verstappen.jpg'],
    concept: 'Um conceito de corrida que mistura grandiosidade esportiva com clima cinematográfico.',
    brief: 'A intenção foi trazer o drama do esporte para uma experiência visual editorial.',
    breakdown: 'Elementos de velocidade são trabalhados como cortes de edição e luz móvel.' ,
    final: 'A última imagem tem presença de grande escala e energia intensa.'
  },
  {
    id: 'superman',
    title: 'The New Son of Krypton',
    category: 'Concept Art',
    year: '2025',
    description: 'Concept art inspirada no Superman de James Gunn.',
    hero: 'img/Superman DESIGN.jpg',
    gallery: ['projeto09.img/Superman 03.jpg', 'projeto09.img/superman 02.jpg', 'img/Superman01.jpg'],
    concept: 'Um retrato heróico com textura e drama, inspirado em storytelling moderno.',
    brief: 'O projeto explora como um personagem icônico se comporta em um quadro cinematográfico.',
    breakdown: 'Contraste de cores, luz no personagem e negative space definem o ritmo visual.' ,
    final: 'A peça final é pensada como o clímax de um pôster de filme.'
  },
  {
    id: 'champions',
    title: 'Composição Visual de Glória e Unidade',
    category: 'Editorial',
    year: '2024',
    description: 'A arte utiliza uma composição centrada na celebração coletiva, reforçando a narrativa de conquista.',
    hero: 'projeto13.img/champions league.jpg',
    gallery: ['projeto13.img/champions league 2.jpg', 'projeto13.img/01.mp4'],
    concept: 'Uma peça criada para evocar triunfo e movimento em uma única imagem editorial.',
    brief: 'O projeto combina cultura visual e emoção esportiva com linguagem gráfica refinada.',
    breakdown: 'A composição enfatiza liderança e união por meio de escala e posicionamento.' ,
    final: 'A cena final se apresenta como um momento icônico de vitória.'
  },
  {
    id: 'fantastic-four',
    title: 'Fantastic Four Reimagined – Visual Concept Art (2025)',
    category: 'Poster Concept',
    year: '2025',
    description: 'arte (2025) cartaz. Reinterpretação visual.',
    hero: 'img/Fantastic Four.jpg',
    gallery: ['projeto10.img/Fantastic Four.jpg'],
    concept: 'Uma releitura cinematográfica de uma equipe clássica, com clima editorial e drama de luz.',
    brief: 'O foco é construir identidade em um formato que se assemelha a um pôster de filme moderno.',
    breakdown: 'O uso de cor e escala cria hierarquia e propósito visual.' ,
    final: 'O resultado final é uma imagem marcante com presença de tela grande.'
  },
  {
    id: 'oppenheimer',
    title: 'Oppenheimer Concept',
    category: 'Film Tribute',
    year: '2025',
    description: 'Homenagem visual ao universo de Oppenheimer.',
    hero: 'projeto17.img/Oppenheimer.jpg',
    gallery: ['projeto17.img/Oppenheimer 02.jpg'],
    concept: 'Um tributo visual que usa textura e atmosfera para criar uma sensação de suspense histórico.',
    brief: 'A peça busca ser ao mesmo tempo elegante e tensa, com foco em valor dramático.',
    breakdown: 'Contrastes fortes e composição de alto impacto estruturam o visual.' ,
    final: 'A imagem final funciona como o frame de um filme prestes a explodir em emoção.'
  },
  {
    id: 'the-godfather',
    title: 'The Godfather — Visual Study',
    category: 'Film Study',
    year: '2025',
    description: 'Conceito inspirado no clássico The Godfather.',
    hero: 'projeto16.img/The Godfather.jpg',
    gallery: ['projeto16.img/The Godfather  02.jpg', 'projeto16.img/The Godfather  03.jpg', 'projeto16.img/The Godfather  04.jpg'],
    concept: 'Uma imagem de clima pesado e contraste extremo, com influência de cinema noir.',
    brief: 'O projeto se apoia em narrativa visual para transmitir poder e mistério.',
    breakdown: 'Luzes pontuais e texturas escuras ressaltam a dramaticidade.' ,
    final: 'O visual final lembra grandes cenas de filmes clássicos.'
  },
  {
    id: 'ghost-shell',
    title: 'Ghost in the Shell Concept',
    category: 'Sci-Fi Concept',
    year: '2025',
    description: 'Conceito inspirado em Ghost in the Shell.',
    hero: 'projeto18.img/Ghost in the Shell 02.jpg',
    gallery: ['projeto18.img/Ghost in the Shell 02 copiar.jpg', 'projeto18.img/Ghost in the Shell 04copiar.jpg'],
    concept: 'Uma imagem cyberpunk com textura suave e presença de neon frio.',
    brief: 'O trabalho prioriza atmosfera, profundidade e uma sensação imersiva de futurismo.' ,
    breakdown: 'Elementos tecnológicos são apresentados como camadas luminosas e transparências.' ,
    final: 'A cena final captura um universo distópico com estética de trailer.'
  },
  {
    id: 'matrix',
    title: 'Matrix — Visual Identity',
    category: 'Sci-Fi Poster',
    year: '2025',
    description: 'Conceito inspirado em Matrix.',
    hero: 'projeto19.img/Matrix copiar.jpg',
    gallery: ['projeto19.img/Matrix copiar 02.jpg', 'projeto19.img/Matrix copiar 03.jpg'],
    concept: 'Um universo digital criado para evocar inquietação e controle visual.',
    brief: 'O projeto constrói uma identidade escura e eletrizante, com ritmo cinematográfico.',
    breakdown: 'Contraste de verde, preto e brilho metálico definem a estética.' ,
    final: 'A imagem final é um frame distópico carregado de energia e mistério.'
  },
  {
    id: 'interstellar',
    title: 'Interestelar — Concept Scene',
    category: 'Film Concept',
    year: '2025',
    description: 'Uma cena visual inspirada em Interestelar.',
    hero: 'projeto15.img/Interestelar.jpg',
    gallery: ['projeto15.img/Interestelar copiar.jpg'],
    concept: 'Uma composição que usa espaço e contraste para sugerir grandeza cósmica.',
    brief: 'A peça explora silêncio e escala para criar uma atmosfera épica e cinematográfica.',
    breakdown: 'Luz suave e texturas profundas reforçam a sensação de universo em expansão.' ,
    final: 'O resultado funciona como um frame de uma jornada visual.'
  }
];
